name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Or our default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Adjust this to the version we need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lektor

      # Build with Lektor specifying the output directory explicitly
      - name: Build site with Lektor
        run: lektor build --output-path .lektoroutput
        # ".lektoroutput" is the directory where the site will be built;
        # adjust to taste!

      # Add CNAME to the build directory
      - name: Add CNAME
        run: echo "www.gaudengalea.com" > .lektoroutput/CNAME
        # Adjust to the custom domain and build directory.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN is generated in the action itself and deleted afterwards;
          # no manual action is needed, reducing risk of secrets leaking.
          publish_dir: ./.lektoroutput
          # Make sure this matches the directory specified in the build step.
